export const GoodsAndClasses=[
    '1 - hemijski proizvodi',
    '2 - boje, firnajzi, lakovi',
    '3 - nemedicinska kozmetika i toaletni papir',
    '4 - industrijska ulja, masti i vosak',
    '5 - farmaceutski i drugi preparati za medicinske ili veterinarske svrhe',
    '6 - metali, rude i proizvodi od metala',
    '7 - mašine, mašinski alati, motori',
    '8 - alati kojima se ručno upravlja',
    '9 - aparati i instrumenti za naučne, istraživačke namene, oprema za audiovizuelne i informacione tehnologije',
    '10 - hiruški, medicinski, stomaatološki i veterinarski alati',
    '11 - uređaji i instalacije za kontrolu okruženja, osvetljenje, kuvanje, hlađenje i sanitarne svrhe',
    '12 - vozila',
    '13 - vatreno oružje i pirotehnički proizvodi',
    '14 - dragoceni metali, nakit, (polu)drago kamenje, časovnici i satovi',
    '15 - muzički instrumenti i dodaci',
    '16 - papir, karton i njihovi proizvodi, kancelarijski materijal',
    '17 - električni, termički i zvučno izolacioni materijali i plastika',
    '18 - koža i imitacija kože i njihovi proizvodi',
    '19 - nemetalni građevinski materijali',
    '20 - delovi nameštaja',
    '21 - mali ručni pribor i kuhinjski aparati',
    '22 - platna',
    '23 - prirodna ili sintetička preradiva, konci za tekstilnu upotrebu',
    '24 - tekstil i prekrivači za upotrebu u domaćinstvu',
    '25 - odeća, obuća i pokrivala za glavu',
    '26 - krojački artikli, prirodna i veštačka kosa, razni ukrasi',
    '27 - proizvodi za pokrivanje podova i zidova',
    '28 - igračke, sportska oprema, aparati za igranje igrica',
    '29 - prehrambeni proizvodi životinjskog porekla, konzervirano povrće',
    '30 - žitarice i proizvodi od žitarica, začini, sladoled, čokolada, med, dodaci hrani',
    '31 - sirovi plodovi zemlje i mora',
    '32 - bezalkoholna pića i pivo',
    '33 - alkoholna pića, esencije i alkoholni ekstrakti',
    '34 - duvan i njegovi proizvodi, artikli za pušače',
    '35 - poslovno upravljenje, poslovanje, organizovanje i upravljenje trgovačkim/industrijskim preduzećem, oglašavanje, marketing',
    '36 - bankarske usluge i finansijske transakcije, osiguranje nekretnina, finansijska procena',
    '37 - građevinske usluge, restauracija objekata',
    '38 - usluge telekomunikacije',
    '39 - transportne usluge i skladištenje',
    '40 - obrađivanje materijala, prečišćavanje, štampanje, konzervisanje namirnica i pića',
    '41 - usluge obrazovanja i obuke, sportske i kulturne aktivnosti',
    '42 - usluge naučnih laboratorija, inženjerstva, dizajna, programiranja',
    '43 - usluge obezbeđivanja hrane i pića i privremeni smeštaj',
    '44 - medicinske i veterinarske usluge, higijenska zaštita i nega lepote, usluge poljoprivrede, akvakulture, hortikulture i šumarstva',
    '45 - pravne usluge, usluge obezbeđenja, pogrebe usluge'
]
