export const PATENT = 'PATENT'
export const STAMP = 'STAMP'
export const PATENT_OFFICIAL = 'PATENT-ALL'
export const OFFICIAL = 'ALL'
export const AUTHORSHIP = 'AUTHORSHIP'
export const AUTHORSHIP_OFFICIAL = 'AUTHORSHIP-ALL'
